---
driver_plugin: vagrant

driver_config:
  customize:
    cpus: 2
    memory: 1024

provisioner:
  name: chef_zero
  require_chef_omnibus: true
  attributes:
    docker:
      container_cmd_timeout: 30

platforms:
- name: centos-6.5-chef-12.4.3
  driver_config:
    require_chef_omnibus: 12.4.3
    box: opscode-centos-6.5
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box

- name: centos-7.0-chef-12.4.3
  driver_config:
    require_chef_omnibus: 12.4.3
    box: opscode-centos-7.0
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.0_chef-provisionerless.box

# *shakes fist at systemd*
- name: debian-8.1-chef-12.4.3
  driver_config:
    require_chef_omnibus: 12.4.3
    box: opscode-debian-8.1
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-8.1_chef-provisionerless.box

- name: fedora-21-chef-12.4.3
  driver_config:
    require_chef_omnibus: 12.4.3
    box: opscode-fedora-21
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_fedora-21_chef-provisionerless.box

- name: ubuntu-12.04-chef-12.4.3
  run_list:
    - recipe[apt]
  driver_config:
    require_chef_omnibus: 12.4.3
    box: opscode-ubuntu-12.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box

- name: ubuntu-14.04-chef-12.4.3
  run_list:
    - recipe[apt]
  driver_config:
    require_chef_omnibus: 12.4.3
    box: opscode-ubuntu-14.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box

- name: ubuntu-15.04-chef-12.4.3
  run_list:
    - recipe[apt]
  driver_config:
    require_chef_omnibus: 12.4.3
    box: opscode-ubuntu-15.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-15.04_chef-provisionerless.box

- name: centos-6.5-chef-latest
  driver_config:
    box: opscode-centos-6.5
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box

- name: centos-7.0-chef-latest
  driver_config:
    box: opscode-centos-7.0
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.0_chef-provisionerless.box

# *shakes fist at systemd*
- name: debian-8.1-chef-latest
  driver_config:
    box: opscode-debian-8.1
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-8.1_chef-provisionerless.box

- name: fedora-21-chef-latest
  driver_config:
    box: opscode-fedora-21
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_fedora-21_chef-provisionerless.box

- name: ubuntu-12.04-chef-latest
  run_list:
    - recipe[apt]
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box

- name: ubuntu-14.04-chef-latest
  run_list:
    - recipe[apt]
  driver_config:
    box: opscode-ubuntu-14.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box

- name: ubuntu-15.04-chef-latest
  run_list:
    - recipe[apt]
  driver_config:
    box: opscode-ubuntu-15.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-15.04_chef-provisionerless.box


suites:
#
# Resource behavior testing cookbooks
#
- name: service-socket-execute
  includes: [
    'ubuntu-15.04-chef-12.4.3',
    'ubuntu-15.04-chef-latest'
  ]
  attributes:
    docker:
      version: '1.8.2'
      service_manager: execute
  run_list:
  - recipe[docker_service_test::socket]

- name: service-tls-execute
  includes: [
    'ubuntu-15.04-chef-12.4.3',
    'ubuntu-15.04-chef-latest'
  ]
  attributes:
    docker:
      version: '1.8.2'
      service_manager: execute
  run_list:
  - recipe[docker_service_test::tls]

- name: service-socket
  includes: [
    'amazon-2014.09-chef-12.4.3',
    'amazon-2014.09-chef-latest',
    'fedora-21-chef-12.4.3',
    'fedora-21-chef-latest',
    'centos-6.5-chef-12.4.3',
    'centos-6.5-chef-latest',
    'centos-7.0-chef-12.4.3',
    'centos-7.0-chef-latest',
    'debian-7.0-chef-12.4.3',
    'debian-7.0-chef-latest',
    'debian-8-chef-12.4.3',
    'debian-8-chef-latest',
    'ubuntu-12.04-chef-12.4.3',
    'ubuntu-12.04-chef-latest',
    'ubuntu-14.04-chef-12.4.3',
    'ubuntu-14.04-chef-latest',
    'ubuntu-15.04-chef-12.4.3',
    'ubuntu-15.04-chef-latest'
  ]
  attributes:
    docker:
      service_manager: system
  run_list:
  - recipe[docker_service_test::socket]

- name: service-tls
  includes: [
    'amazon-2014.09-chef-12.4.3',
    'amazon-2014.09-chef-latest',
    'fedora-21-chef-12.4.3',
    'fedora-21-chef-latest',
    'centos-6.5-chef-12.4.3',
    'centos-6.5-chef-latest',
    'centos-7.0-chef-12.4.3',
    'centos-7.0-chef-latest',
    'debian-7.0-chef-12.4.3',
    'debian-7.0-chef-latest',
    'debian-8-chef-12.4.3',
    'debian-8-chef-latest',
    'ubuntu-12.04-chef-12.4.3',
    'ubuntu-12.04-chef-latest',
    'ubuntu-14.04-chef-12.4.3',
    'ubuntu-14.04-chef-latest',
    'ubuntu-15.04-chef-12.4.3',
    'ubuntu-15.04-chef-latest'
  ]
  attributes:
    docker:
      service_manager: system
  run_list:
  - recipe[docker_service_test::tls]

- name: resources-162
  includes: [
    'debian-8.1-chef-12.4.3',
    'debian-8.1-chef-latest',
    'centos-7.0-chef-12.4.3',
    'centos-7.0-chef-latest',
    'fedora-21-chef-12.4.3',
    'fedora-21-chef-latest',
    'ubuntu-14.04-chef-12.4.3',
    'ubuntu-14.04-chef-latest',
    'ubuntu-15.04-chef-12.4.3',
    'ubuntu-15.04-chef-latest'
  ]
  attributes:
    docker:
      version: '1.6.2'
  run_list:
  - recipe[docker_test::default]
  - recipe[docker_test::image]
  - recipe[docker_test::container]

- name: resources-171
  includes: [
    'debian-8.1-chef-12.4.3',
    'debian-8.1-chef-latest',
    'centos-7.0-chef-12.4.3',
    'centos-7.0-chef-latest',
    'fedora-21-chef-12.4.3',
    'fedora-21-chef-latest',
    'ubuntu-15.04-chef-12.4.3',
    'ubuntu-15.04-chef-latest'
  ]
  attributes:
    docker:
      version: '1.7.1'
      service_manager: system
  run_list:
  - recipe[docker_test::default]
  - recipe[docker_test::image]
  - recipe[docker_test::container]

- name: resources-182
  includes: [
    'debian-8.1-chef-12.4.3',
    'debian-8.1-chef-latest',
    'centos-7.0-chef-12.4.3',
    'centos-7.0-chef-latest',
    'fedora-21-chef-12.4.3',
    'fedora-21-chef-latest',
    'ubuntu-15.04-chef-12.4.3',
    'ubuntu-15.04-chef-latest'
  ]
  attributes:
    docker:
      version: '1.8.2'
  run_list:
  - recipe[docker_test::default]
  - recipe[docker_test::image]
  - recipe[docker_test::container]

- name: notifications
  includes: [
    'ubuntu-15.04-chef-12.4.3',
    'ubuntu-15.04-chef-latest'
  ]
  attributes:
    docker:
      version: '1.8.2'
  run_list:
  - recipe[docker_test::notifications]

- name: timeout
  includes: [
    'ubuntu-15.04-chef-12.4.3',
    'ubuntu-15.04-chef-latest'
  ]
  attributes:
    docker:
      version: '1.8.2'
  run_list:
  - recipe[docker_test::timeout]
