---
driver_plugin: vagrant

driver_config:
  customize:
    memory: 1024

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.4.4.box
    require_chef_omnibus: 11.4.4

suites:
- name: image_lwrp
  run_list:
  - recipe[minitest-handler]
  - recipe[docker_test::default]
  - recipe[docker_test::image_lwrp]
  - recipe[docker_test::container_lwrp]
  attributes: {}
